name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: ssh-keyscan -H 18.175.216.204 >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh ubuntu@18.175.216.204 << 'EOF'
            cd ~/magnet-to-stream-microservice/t2s

            # Write .env file from GitHub secret
            echo "${{ secrets.ENV_FILE }}" > .env

            # Pull latest code and install dependencies
            git pull origin main
            npm install

            # Restart service with pm2
            pm2 restart magnet-stream || pm2 start npm --name "magnet-stream" -- run dev
            pm2 save
          EOF
