name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: ssh-keyscan -H ec2-3-11-9-31.eu-west-2.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh ubuntu@ec2-3-11-9-31.eu-west-2.compute.amazonaws.com << 'EOF'
            cd ~/magnet-to-stream-microservice/t2s

            echo "${{ secrets.ENV_FILE }}" > .env
            git pull origin main
            npm install
            pm2 restart magnet-stream || pm2 start npm --name "magnet-stream" -- run dev
            pm2 save
          EOF
