name: Deploy to VPS

on:
  push:
    branches:
      - main  # Change this if you deploy from a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 18.175.216.204 >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@18.175.216.204 << 'EOF'
            cd ~/magnet-to-stream-microservice/t2s-bmad

            # Write .env file from GitHub secret
            echo "${{ secrets.ENV_FILE }}" > .env

            # Pull latest code and install dependencies
            git pull origin main
            npm install

            # Restart service with pm2
            pm2 restart magnet-stream || pm2 start npm --name "magnet-stream" -- run dev
            pm2 save
          EOF
